package com.tyss.optimize.common.util;

import java.util.*;

public class CommonConstants {

    public static final Float DEFAULT_VERSION = 1.0f;
    public static final Float NEW_VERSION = 0.0f;
    public static final String ANONYMOUS_USER = "USR1";
    public static final String MAX_TWO_SUPER_ADMINS_MESSAGE = "More than 2 super admins are not allowed per license";
    public static final String PROJECT_TYPES = "project.types";
    public static final String YES = "Y";
    public static final String NO = "N";
    public static final String ROOT = "Root";
    public static final String STEP_GROUP = "STEP_GROUP";
    public static final String SCRIPTS = "scripts";
    public static final String UPDATE_TAG = "UPDATE";
    public static final String CREATE_TAG = "CREATE";
    public static final String DELETE_TAG = "DELETE";
    public static final String RESOLVE_TAG = "RESOLVE";
    public static final String None = "None";
    public static final String DFC = "DFC";
    public static final String STATE_COMMIT = "COMMIT";
    public static final String STATE_PUBLISH = "PUBLISH";
    public static final String STATE_RB = "ROLLBACK";
    public static final String STATE_REMOVE = "DELETE";

    public static String Hello = "Hello";
    public static final String EMPTY = "";
    public static final String DOUBLE_COLON = "::";
    public static final String SINGLE_DOT = ".";

    public static Map<String, String> sequenceGenMap = initMap();

    private static Map<String, String> initMap() {
        Map<String, String> sequenceMap = new HashMap<>();
        sequenceMap.put("PROJECT", "PJT");
        sequenceMap.put("PAGE", "PAG");
        sequenceMap.put("USER", "USR");
        sequenceMap.put("DEFAULT", "DEF");
        sequenceMap.put("ELEMENT", "ELE");
        sequenceMap.put("MODULE", "MOD");
        sequenceMap.put("STEP", "STE");
        sequenceMap.put("SCRIPT", "SCR");
        sequenceMap.put("ROLE", "ROLE");
        sequenceMap.put("USER_ROLE", "USER_ROLE");
        sequenceMap.put("LICENSE", "LIC");
        sequenceMap.put("PACKAGE", "PKJ");
        sequenceMap.put("FOLDER", "FLDR");
        sequenceMap.put("LIBRARY", "LIB");
        sequenceMap.put("STEP_GROUP", "STP_GRP");
        sequenceMap.put("PROGRAM_ELEMENT", "PRG_ELE");
        sequenceMap.put("NLP_METADATA", "NLP");
        sequenceMap.put("NLP", "NLP");
        sequenceMap.put("FILE", "FILE");
        sequenceMap.put("PE_NLP", "PE_NLP");
        sequenceMap.put("PRE_POST_CONDITION", "PE_POST_COND");
        sequenceMap.put("DATA_PROVIDER", "DATA_PROVIDER");
        sequenceMap.put("EMAIL_TEMPLATE", "EMT");
        sequenceMap.put("LABEL_GROUP", "LABEL_GROUP");
        sequenceMap.put("LICENSE_TYPE", "LIC_TYPE");
        sequenceMap.put("LABEL", "LABEL");
        sequenceMap.put("LICENSE_PLAN", "LIC_PLAN");
        sequenceMap.put("LIMIT", "LIMIT");
        sequenceMap.put("PROJECT_TYPE", "PJT_TYPE");
        sequenceMap.put("VARIABLE", "VAR");
        sequenceMap.put("QUICK_RUN_SETTINGS", "QRS");
        sequenceMap.put("EXECUTIONRESPONSE", "EXR");
        sequenceMap.put("DEPENDENT_SCRIPT", "DEP_SCR");
        sequenceMap.put("STEP_GROUP_NLP", "SG_NLP");
        sequenceMap.put("EXECUTION", "EXEC");
        sequenceMap.put("PARAMETER", "PARAMETER");
        sequenceMap.put("SUITE", "SUITE");
        sequenceMap.put("SUITE_OF_SUITES", "SOS");
        sequenceMap.put("SHARED_ELEMENT", "SH_ELE");
        sequenceMap.put("RECORDED_ELEMENT", "RD_ELE");
        sequenceMap.put("CLIENT_SYSTEM_CONFIG", "SCDR");
        sequenceMap.put("EMAIL_GROUP", "EMAIL_GROUP");
        sequenceMap.put("VARIABLE_SET", "VARIABLE_SET");
        sequenceMap.put("TEST_DATA_SET", "TEST_DATA_SET");
        sequenceMap.put("LICENSE_DEFAULT", "LIC_DEFAULT");
        sequenceMap.put("DATATYPE", "DTP");
        sequenceMap.put("STORAGE_CONFIG", "STR");
        sequenceMap.put("WAIT_CONFIG", "WT_CFG");
        sequenceMap.put("RESULT_CONFIG", "RES_CFG");
        sequenceMap.put("HISTORY_CONFIGURATION", "HIS_CFG");
        sequenceMap.put("ELEMENT_TYPE", "ELE_TYPE");
        sequenceMap.put("LOCATOR_TYPE", "LOC_TYPE");
        sequenceMap.put("BROWSERSTACK", "BROWS");
        sequenceMap.put("SCREEN_SHOT_VIDEO_CONFIG", "SCR_VIDEO_CFG");
        sequenceMap.put("DEFAULT_PROJECT_ELEMENT", "DEF_PJT_ELE");
        sequenceMap.put("SAUCELABS", "SAUCE");
        sequenceMap.put("DRIVER_CONFIG", "DC");
        sequenceMap.put("SCHEDULE", "SCHE");
        sequenceMap.put("JIRA", "JIRA");
        sequenceMap.put("LAMBDATEST", "LAMBDA");
        sequenceMap.put("TAGDETAIL", "TAG");
        sequenceMap.put("DEFAULT_CONFIGURATIONS", "DCONF");
        sequenceMap.put("STORAGE_DETAIL", "STRC");
        sequenceMap.put("STORAGE_SNAPSHOT", "SNAP");
        sequenceMap.put("SCRIPT_TEMPLATE", "TEMP");
        sequenceMap.put("SLACK", "SLACK");
        sequenceMap.put("GITLAB", "GITLAB");
        sequenceMap.put("GITHUB", "GITHUB");
        sequenceMap.put("DEFECT_TEMPLATE", "DEFTEMP");

        return Collections.unmodifiableMap(sequenceMap);
    }

    public static String DB_PREFIX = "DB_PREFIX";
    public static String MONGO_AUTH_DB = "MONGO_AUTH_DB";
    public static String SUCCESS = "SUCCESS";
    public static String FAILURE = "FAILURE";
    public static final String TOKEN_INVALID = "Token is invalid";
    public static final String ALREADY_EXIST = " already exist";
    public static final String DEFAULT_ANDROID_FLD = "Default-Android";
    public static final String DEFAULT_IOS_FLD = "Default-iOS";
    public static final String DEFAULT_ICON = "--";
    public static final String UNAUTHORIZED = "You are not authorized";
    public static final String FULL_ACCESS_ROLE = "Full Access";
    public static final String EXECUTE_ACCESS_ROLE = "Execute Access";
    public static final String DEFAULT_FULL_ACCESS_ID = "ROLE1001";
    public static final String DEFAULT_EXECUTE_ACCESS_ID = "ROLE1002";
    public static final String INACTIVE_USER = "User is not activated";
    public static final String IS_SECOND_SUPER_ADMIN = "isSecondSuperAdmin";
    public static final String INVALID_USER = "EmailId or Password is invalid. Please try again";
    public static final String STATIC = "static";
    public static final String DYNAMIC = "dynamic";
    public static final String STATE_NEW = "NEW";
    public static final String DEFAULT_EXPORT_FLD = "Export_Script_Files";
    public static final String DEFAULT_JAR_FLD = "Custom-JAR";
    public static final String FINAL_JAR_FLD = "Final-JAR";
    public static final String DEFAULT_DATATYPE_ID = "DTP1001";
    public static final String DEFAULT_STORAGE_CONFIG_ID = "STR1001";
    public static final String DEFAULT_ELEMENT_ONE = "DEF_ELE1001";
    public static final String DEFAULT_ELEMENT_TWO = "DEF_ELE1002";
    public static final String DEFAULT_ELEMENT_THREE = "DEF_ELE1003";
    public static final String DEFAULT_ELEMENT_FOUR = "DEF_ELE1004";
    public static final String DEFAULT_ELEMENT_FIVE = "DEF_ELE1005";
    public static final String DEFAULT_ELEMENT_SIX = "DEF_ELE1006";
    public static final String DEFAULT_ELEMENT_SEVEN = "DEF_ELE1007";
    public static final String DEFAULT_ELEMENT_EIGHT = "DEF_ELE1008";
    public static final String DEFAULT_ELEMENT_NINE = "DEF_ELE1009";
    public static final String DEFAULT_ELEMENT_TEN = "DEF_ELE1010";
    public static final String DEFAULT_ELEMENT_ELEVEN = "DEF_ELE1011";
    public static final String DEFAULT_ELEMENT_TWELVE = "DEF_ELE1012";
    public static final String DEFAULT_ELEMENT_THIRTEEN = "DEF_ELE1013";
    public static final String DEFAULT_ELEMENT_FOURTEEN = "DEF_ELE1014";

    public static final String DEFAULT_STEPGROUP_ONE = "STP_GRP1001";
    public static final String DEFAULT_STEPGROUP_TWO = "STP_GRP1002";
    public static final String DEFAULT_STEPGROUP_THREE = "STP_GRP1003";
    public static final String DEFAULT_STEPGROUP_FOUR = "STP_GRP1004";
    public static final String DEFAULT_STEPGROUP_FIVE = "STP_GRP1005";
    public static final String DEFAULT_STEPGROUP_SIX = "STP_GRP1006";
    public static final String DEFAULT_LIBRARY_WEB = "Open and Close Browser";
    public static final String DEFAULT_LIBRARY_MOBILE = "Open and Close App";
    public static final String DEFAULT_NLP_ANDROID_OPEN = "Open Android App";
    public static final String DEFAULT_NLP_ANDROID_CLOSE = "Close Android App";
    public static final String DEFAULT_NLP_IOS_OPEN = "Open iOS App";
    public static final String DEFAULT_NLP_IOS_CLOSE = "Close iOS App";
    public static final String BROWSER_NAME = "browserName";
    public static final String DEVICE_NAME = "deviceName";
    public static final String URL = "URL";
    public static final String PLATFORM_NAME = "platformName";
    public static final String PLATFORM_NAME_ANDROID = "platformNameAOS";
    public static final String PLATFORM_NAME_IOS = "platformNameiOS";
    public static final String APP_PACKAGE = "appPackage";
    public static final String APP_ACTIVITY = "appActivity";
    public static final String BUNDLE_ID = "bundleID";
    public static final String CAPABILITY = "cap";
    public static final String KEY = "key";
    public static final String VALUE = "value";

    public static final String DEFAULT_LOCATORS = "Default Locators";
    public static final String DEFAULT_WAIT_CONFIG = "WT_CFG1000";
    public static final String DEFAULT_RESULT_CONFIG = "RES_CFG1000";
    public static final String DEFAULT_SCREEN_SHOT_VIDEO_CONFIG = "SCR_VIDEO_CFG1000";
    public static final String DEFAULT_HISTORY_CONFIG = "HIS_CFG1000";
    public static final String DEFAULT_DATE_TIME_CONFIG = "DATE_TIME_CFG1000";
    public static final String DEFAULT_MEMORY_CONFIG_ID = "MEM_CFG1000";
    public static final String DEFAULT_CONFIGURATIONS_ID = "DF_CONFS1000";

    public static final Integer FILENAME_MAX = 25;
    public static final Integer FILENAME_MIN = 2;
    public static final String FILENAMESIZE_ALERT = "File name must be minimum " + FILENAME_MIN + " characters";

    public static final Integer PARAM_NAME_MAX = 25;
    public static final Integer PARAM_NAME_MIN = 3;
    public static final String PARAM_NAME_SIZE_ALERT = "Parameter name must be minimum " + PARAM_NAME_MIN + " and maximum " + PARAM_NAME_MAX + " characters";

    public static final Integer COMPONENTS_COUNT_MIN = 5;

    public static final Integer SCREEN_SHOT_MIN_DAYS = 365;
    public static final Integer VIDEO_MIN_DAYS = 365;

    public static final Double TOTAL_MEMORY = 10.0;
    public static final String TOTAL_MEMORY_UNIT = "GB";
    public static final String DEFAULT_MEMORY_UNIT = "MB";
    public static final Double USED_MEMORY = 0.0;
    public static final String USED_MEMORY_UNIT = "GB";
    public static final Double AVAILABLE_MEMORY = 10.0;
    public static final Double DEFAULT_PROJECT_MEMORY = 200.0;
    public static final String AVAILABLE_MEMORY_UNIT = "GB";
    public static final Integer PROJECT_COUNT_MIN = 0;

    public static final String DEFAULT_DATE_FORMAT = "dd-mm-yyyy";
    public static final String DEFAULT_DATE_SEPARATOR = "-";
    public static final String DEFAULT_TIME_FORMAT = "hh-mm-ss";
    public static final String DEFAULT_TIME_ZONE = "(UTC+05:30) Chennai,Kolkata,Mumbai,New Delhi";

    public static final String DEFAULT_VIEW_NAME = "Default_View";
    public static final String DEFAULT_VIEW_ALL_COLUMNS = "noOfElements,sharedElements,elementType,version,newCommitPublish,locators,lastModifiedBy,delete,createdBy,createdOn,lastModifiedOn,description";

    public static final Integer COMPONENTS_RESULT_MIN = 200;

    public static final Double EXPLICIT_WAIT = 20.0;
    public static final String EXPLICIT_WAIT_UNIT = "seconds";
    public static final Double IMPLICIT_WAIT = 20.0;
    public static final String IMPLICIT_WAIT_UNIT = "seconds";
    public static final Double DELAY_BETWEEN_STEPS = 0.0;
    public static final String DELAY_BETWEEN_STEPS_UNIT = "seconds";

    public static final Integer RD_ELEMENT_NAME_MAX = 100;
    public static final Integer RD_ELEMENT_NAME_MIN = 2;
    public static final String RD_ELEMENT_NAME_SIZE_ALERT = "Recorded Element name must be minimum " + RD_ELEMENT_NAME_MIN + " and maximum " + RD_ELEMENT_NAME_MAX + " characters";


    // AUTH ROLES
    public static final String FULL_ACCESS = "FULL_ACCESS";
    public static final String NO_ACCESS = "NO_ACCESS";
    public static final String VIEW = "VIEW";
    public static final String WRITE = "WRITE";

    public static final List<String> fancyTreeFolderList = Arrays.asList("PAG", "LIB", "MOD", "FLDR", "EXR", "PKJ", "FLD");
    public static final List<String> timeInSecondsUnit = Arrays.asList("Secs", "Seconds", "Secs.");
    public static final List<String> timeInMilliSecondsUnit = Arrays.asList("MilliSeconds", "Milliseconds", "MilliSec", "Msecs");
    public static final List<String> timeInHoursUnit = Arrays.asList("Hours", "Hrs.");
    public static final List<String> timeInMinutesUnit = Arrays.asList("Minutes", "Mins.");
    public static final List<String> envToValidate = Arrays.asList("Localhost", "Local", "localhost", "local");

    //Execution Client related Constants
    public static String API = "/optimize";
    public static String version = "/v1";
    public static String baseUrl = API + version;
    public static String successMsg = "Success";
    public static String failMsg = "Failed";
    public static String badRequest = "Bad Request";
    public static String alreadyExist = "Already Exist";
    public static String notFoundMsg = "Data Not Found";
    public static Integer successCode = 0;
    public static Integer errorCode = -1;
    public static String nullValue = null;
    public static String running = "Running";
    public static String pending = "Pending";
    public static String completed = "Completed";
    public static String busy = "Busy";
    public static String available = "Available";
    public static String aborted = "Aborted";
    public static final String pass = "PASS";
    public static final String fail = "FAIL";
    public static final String skip = "SKIP";
    public static final String NA = "N/A";
    public static final String warning = "WARNING";
    public static String preCondition = "preCondition";
    public static String postCondition = "postCondition";
    public static String executionEntityResponses = "executionEntityResponses";
    public static String dependantExecutionEntityResponses = "dependantExecutionEntityResponses";
    public static String dot = ".";
    public static String script = "Script";
    public static String module = "Module";
    public static String group = "Group";
    public static String step = "step";
    public static String booleanTrue = "true";
    public static String booleanFalse = "false";

    public static String reports = "./Reports/";
    public static String ifCondition = "IfCondition";
    public static String elseIfCondition = "ElseIfCondition";
    public static String elseCondition = "ElseCondition";
    public static String endIfCondition = "EndIfCondition";
    public static String endElseIfCondition = "EndElseIfCondition";
    public static String endElseCondition = "EndElseCondition";
    public static String parentIfCondition = "parentIfCondition";
    public static String stepName = "stepName";
    public static String conditionName = "conditionName";
    public static String conditionStatus = "conditionStatus";
    public static String dollar = "$";
    public static String colon = ":";
    public static String openCurlyBrace = "{";
    public static String closeCurlyBrace = "}";
    public static String underScore = "_";
    public static String forwardSlash = "/";
    public static String iteration = "Iteration";
    public static String forCondition = "ForCondition";
    public static String endIteration = "EndIteration";
    public static String endForCondition = "EndForCondition";
    public static String dataProviderName = "dataProviderName";
    public static final String typeBoolean = "java.lang.Boolean";
    public static final String typeInteger = "java.lang.Integer";
    public static final String typeLong = "java.lang.Long";
    public static final String typeShort = "java.lang.Short";
    public static final String typeByte = "java.lang.Byte";
    public static final String typeCharacter = "java.lang.Character";
    public static final String typeFloat = "java.lang.Float";
    public static final String typeDouble = "java.lang.Double";
    public static final String typeString = "java.lang.String";
    public static final String typeListOfString = "List<String>";
    public static final String typeJSONObject = "org.json.simple.JSONObject";
    public static String responseToServer = "Execution request is received and being processed";
    public static final String ifConditionNlpName = "IfCondition";
    public static final String endIfConditionNlpName = "EndIfCondition";
    public static final String elseIfConditionNlpName = "ElseIfCondition";
    public static final String endElseIfConditionNlpName = "EndElseIfCondition";
    public static final String elseConditionNlpName = "ElseCondition";
    public static final String endElseConditionNlpName = "EndElseCondition";
    public static final String startIterationNlpName = "StartIteration";
    public static final String endIterationNlpName = "EndIteration";
    public static final String startForLoopNlpName = "StartForLoop";
    public static final String endForLoopNlpName = "EndForLoop";
    public static final String typeLocal = "LOCAL";
    public static final String typeGlobal = "GLOBAL";
    public static final String typeStepGroup = "STEPGROUP";
    public static final String typeDataProvider = "DATAPROVIDER";
    public static final String typeProjectEnvironment = "PROJECTENVIRONMENT";
    public static final String projectEnvironmentType = "PROJECT_ENVIRONMENT";
    public static String tillLastRow = "Till Last Row";
    public static String systemId = "systemId";
    public static String startIterationCount = "startIterationCount";

    //public static String IDENTIFIER = "http://";
    public static String IDENTIFIERs = "http://";
    public static String serverSideExecutionResponseURI = "/optimize/v1/executionResponse";
    public static String clientSystemConfigUpdateExecutionStatusURI = "/optimize/v1/clientSystemConfig";
    public static String token = "token";
    public static String serverHost = "serverHost";
    public static String serverPort = "serverPort";
    public static String resultSyncPort = "resultSyncPort";
    public static String RESOURCE_NAME = "/optimize/v1/executions/result";
    public static String dashboardResourceName = "/optimize/v1/dashboard/execution";
    public static String dashboardStorageResourceName = "/optimize/v1/project/dashboard/storage/";
    public static String dashboardHost = "localhost";
    public static String dashboardPort = "8109";


    public static String analyticsHost ="localhost";
    public static String analyticsPort = "8115";
    public static String analyticsResourceName = "/optimize/v1/analytics";


    public static String terminated = "Terminated";
    public static String cancelled = "Cancelled";
    public static final String enabled = "enabled";
    public static final String disabled = "disabled";
    public static final String Web = "Web";
    public static final String Android = "Android";
    public static final String iOS = "iOS";
    public static final String Webservice = "Webservice";
    public static final String Database = "Database";
    public static final String WebAndMobile = "Web & Mobile";
    public static final String Mobile = "Mobile";
    public static final String Salesforce = "Salesforce";

    public static final String DEFAULT_LOCATOR_ID = "LIC_DEFAULT1001";
    public static final String DEFAULT_LOCATOR_IDS = "LIC_DEFAULT1002";
    public static final String DEFAULT_DYNAMIC_LOCATOR_IDS = "LIC_DEFAULT1003";
    public static final String DEFAULT_VIEW = "DEF_VIEW1001";
    public static final int DEFAULT_LIMIT = 10;
    public static String licenseId = "licenseId";
    public static final String milliSeconds = "MiliSeconds";
    public static final String seconds = "Seconds";
    public static final String forFailedStepsOnly = "For failed steps only";
    public static final String dontCapture = "Don't capture";
    public static String individualType = "INDIVIDUAL";
    public static String suiteType = "SUITE";
    public static String suiteOfSuiteType = "SUITE_OF_SUITES";
    public static String SECRET_KEY = "8my0_4super7_1secret1_5key8";
    public static String SALT = "7X57CKG72JVNSSS9";
    public static String BROWSER = "browser";
    public static String Internet_Explorer = "internet explorer";
    public static String Safari = "safari";
    public static String Firefox = "firefox";
    public static String Microsoft_Edge = "microsoft edge";
    public static String Chrome = "chrome";
    public static String Device = "device";
    public static String Windows = "windows";
    public static String IExplorer = "internet explorer";
    public static String MSedge = "MicrosoftEdge";
    public static String MAC = "mac";
    public static String Linux = "linux";
    public static String Darwin = "darwin";
    public static String internet = "Internet";
    public static String intranet = "Intranet";
    public static String topicPrefix = "consumer-";
    public static String processed = "Processed";
    public static String active = "Active";
    public static String inactive = "Inactive";
    public static String once = "Once";
    public static String daily = "Daily";
    public static String weekly = "Weekly";
    public static String monthly = "Monthly";
    public static String yearly = "Yearly";
    public static String cascaded = "cascaded";
    public static String onlyForFailedSteps = "Only for failed Steps";
    public static String execution = "execution";
    public static final int HISTORY_MIN = 5;
    public static final int HISTORY_MAX = 200;
    public static final int SCREEN_SHOT_MIN = 1;
    public static final int SCREEN_SHOT_MAX = 365;
    public static String testData = "testData";
    public static String screenshots = "screenshots";
    public static String videos = "videos";
    public static String programElement = "programElement";
    public static String ADMIN = "ADMIN";
    public static String programElementJar = "tyss-programelements.jar";
    public static String hubUrlPrefix = "https://";
    public static String osName = "Windows";
    public static String parallel = "Parallel";
    public static String sequential = "Sequential";
    public static String distribute = "Distribute";
    public static String license = "License";
    public static String bytes = "B";
    public static String kilo_byte = "KB";
    public static String mega_byte = "MB";
    public static String giga_byte = "GB";
    public static String tera_byte = "TB";
    public static String BROWSER_STACK_CREDENTIALS_URL = hubUrlPrefix + "api.browserstack.com/automate/browsers.json";
    public static String BROWSER_STACK_UPLOAD_FILE_URL = hubUrlPrefix + "api-cloud.browserstack.com/app-automate/upload";
    public static String BROWSER_STACK_GET_FILES_URL = hubUrlPrefix + "api-cloud.browserstack.com/app-automate/recent_apps";

    public static String LAMBDA_TEST_BROWSER_LIST_URL = hubUrlPrefix + "api.lambdatest.com/automation/api/v1/platforms";
    public static String LAMBDA_TEST_UPLOAD_FILE_URL = hubUrlPrefix + "api.lambdatest.com/automation/api/v1/user-files";
    public static String LAMBDA_TEST_GET_FILES_URL = hubUrlPrefix + "api.lambdatest.com/automation/api/v1/user-files";

    public static String SAUCE_LAB_BROWSER_LIST_URL = hubUrlPrefix + "api.us-west-1.saucelabs.com/rest/v1/info/platforms/all";
    public static String SAUCE_LAB_CREDENTIALS_URL = ".saucelabs.com/team-management/v1/teams";
    public static String SAUCE_LAB_UPLOAD_FILE_URL = ".saucelabs.com/v1/storage/upload";
    public static String SAUCE_LAB_GET_FILES_URL = ".saucelabs.com/v1/storage/files";

    public static String PRE_PROD_HOST_NAME="preprod.flinko.com";
    public static String PROD_HOST_NAME="app.flinko.com";
    public static  String HTTP="http";
    public static String HTTPS="https";
    public static String manual = "Manual";
    public static String automation = "Automation";
    public static String automation_and_manual = "Automation and Manual";
}
